name = "router"
main = "src/index.ts"
compatibility_date = "2024-10-01"

[observability]
enabled = true

[[d1_databases]]
database_name = "router"
database_id = "01ba9542-5f22-47ce-b1d3-d43ab6d88315"
binding = "DB"
